(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (set-front-ptr! item) (set! front-ptr item))
    (define (set-rear-ptr! item)  (set! rear-ptr item))
    (define (empty-queue?) (null? front-ptr))
    (define (front-queue)
      (if (empty-queue?)
          (error "FRONT called with an empty queue")
          (car front-ptr)))
    (define (insert-queue! item)
      (let ((new-pair (cons item '())))
        (cond ((empty-queue?)
               (set-front-ptr! new-pair)
               (set-rear-ptr! new-pair)
               dispatch)
              (else
               (set-cdr! rear-ptr new-pair)
               (set-rear-ptr! new-pair)
               dispatch))))
    (define (delete-queue!)
      (cond ((empty-queue?)
             (error "DELETE! called with an empty queue"))
            (else
             (set-front-ptr! (cdr front-ptr))
             dispatch))) 
    (define (print-queue)
      (display front-ptr)
      (newline))
    (define (dispatch cmd)
      (cond ((eq? cmd 'empty-queue?) (empty-queue?))
			((eq? cmd 'insert-queue!) insert-queue!)
            ((eq? cmd 'delete-queue!) (delete-queue!))
            ((eq? cmd 'front-queue) (front-queue))
            ((eq? cmd 'print-queue) (print-queue))
            (else (error "Unknown cmd -- MAKE-QUEUE" action))))
    dispatch))
